dialog_states = {'1': {'message': 'Good morning!',
                       'buttons': ['Hello', 'Good afternoon', 'Hi!']},
                 '2': {'message': 'May I sit here?',
                       'buttons': ['Yes', 'No', 'Srazu net']},
                 '3': {'message': 'What is your name?',
                       'buttons': ['My name is Sasha', 'I don’t know']},
                 '4': {'message': 'Nice to meet you.',
                       'buttons': ['Nice to meet you too',
                                   'I’m pleased to meet you']},
                 '5': {'message': 'How are you?',
                       'buttons': ['Very good', 'Not bad']},
                 '6': {'message': 'I’m happy to hear that. '
                                  'Where are you from?',
                       'buttons': ['I am from Moscow',
                                   'I live in Omsk', 'Here we go again']},
                 '7': {'message': 'What do you do?',
                       'buttons': ['I am a programmer',
                                   'I am an engineer',
                                   'I work in McDonald’s']},
                 '8': {'message': 'Do you have a car?',
                       'buttons': ['No, I don’t']},
                 '9': {'message': 'I don’t want to tell '
                                  'you anymore. Bye, loser!',
                       'buttons': []}}
